### ISSUE TITLE
Using markdown elements with html emails

### ISSUE THREAD

**Issue by dudeonthehorse** [hteumeuleu/email-bugs#42]
I use nunjucks template engine with my email builder. Markdown is a great tool to make content newsletters.

This is the list of email-safe markdown elements to use:
- paragraphs, images and hyperlinks works fine
- `<h1>`-`<h4>` — really no need more than 4 levels of headings. This elements needs for maximum styling to prevent specific email-client css
- `<ul>` and `<ol>` — we must be careful with horizontal paddings (for normal buiilts rendering)
- `<strong>`, `<em>` — but I'm not sure about `font-style: normal` for `em`. Will it works correct in all clients?

Not safe elements to use in emails:
- `<hr>` — but we can use it with Inky(or another component library) for converting syntax to safe
- `<blockquote>` — [Yandex Mail](https://mail.yandex.ru/) hides `<blockquote>` contents under dropdown spoiler
- `<table>` — I think, it's too monstrous element to use it in markdown. 

Other markdown elements are not so needed imho. What do you think? Is that content useful?

**P.S.** 
You can check out my repo https://github.com/dudeonthehorse/normalize.email.css
I tried to normalize default html elements for best email compatibility. Yes, I know — need to improve my library. I'll do my best. Hope, you'll be interest.

**Comment by revelt** [comment]
@dudeonthehorse it's awesome that you're sharing and I respect that and appreciate a lot. However, I'd like to kindly remind that this is a...

> A repository for documenting bugs in webmails and email applications

Here we are like in a **court room** - if you say a statement, you have to prove it. And we have a court case for each email rendering bug out there.

Many people from different backgrounds and different opinions gather here. Some love markdown, some hate it. Some work for ESP's that have their own walled-garden alternatives. But that's all **opinions** - nothing more.

But here, _we don't deal with opinions_ - we deal with **email bugs** which are _scientific facts_. One can code any way one wants - email bugs will hit everybody equally and everybody will come here because it's universal and objective.

If you really want to document markdown support in email software, the first challenge is that markdown is parsed into HTML _before_ it reaches email software, so strictly speaking there can't be any Markdown bugs in email software, unless latter consumes Markdown instead of HTML.

Do you see my point?

I don't want to appear unkind but it feels like you've got an interesting approach, worth to be seen, just it's the wrong place for it. Maybe an article would be better format?

Again, thank you for sharing and I don't want to discourage or upset. It's the right time, right thing, just at not a right place.

**Comment by dudeonthehorse** [comment]
@revelt got it.

**Comment by hteumeuleu** [comment]
It's definitely an interesting subject and it's great that you're sharing this. But I agree with @revelt this might not be the most adequate place to publish this. This would make a great blog post. Feel free to share it and ping me on Twitter if needed.
