### ISSUE TITLE
Mobile devices and @media queries

### ISSUE THREAD

**Issue by stojjan** [hteumeuleu/email-bugs#44]
Hello there!
I've tested the double <style> with @media query for a mobile devices.
It seems that most of them don't respect it, which is interesting - even these which actually support responsive layout.

https://litmus.com/pub/f69ebc6

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
	<!--[if gte mso 9]>
	<xml>
		<o:OfficeDocumentSettings>
		<o:AllowPNG/>
		<o:PixelsPerInch>96</o:PixelsPerInch>
		</o:OfficeDocumentSettings>
	</xml>
	<![endif]-->
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="format-detection" content="date=no" />
	<meta name="format-detection" content="address=no" />
	<meta name="format-detection" content="telephone=no" />
	<title>Email </title>
	<style type="text/css" media="all">
		@media only screen and (max-device-width: 480px), only screen and (max-width: 480px) {
			.h1-center { color: #fff000 !important; }
		}
	</style>
</head>
<body class="body" style="padding:0 !important; margin:0 !important; display:block !important; min-width:100% !important; width:100% !important; background:#000001; -webkit-text-size-adjust:none;">
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td class="td" style="width:600px; min-width:600px; font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal;">
				<style type="text/css" media="all">
					@media only screen and (max-device-width: 480px), only screen and (max-width: 480px) {
						.h1-center { color: #ff0000 !important; }
					}
				</style>
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<td class="h1-center" style="padding-bottom: 20px; color:#ffffff; font-family:Arial,sans-serif; font-size:16px; line-height:20px; text-align:center;">
							<strong>
								LOVE 'EM (LIKELY).<br />
								HATE 'EM (NEVER).
							</strong>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</body>
</html>
```

Would anyone help me with ideas - How to make that second <style> be respected for mobile?

Thank you,
Stojjan

**Comment by revelt** [comment]
hi Stojjan!

Excuse me upfront for not addressing the requested solution but rather questioning the reasoning behind this practice.

Mobile devices do appear to have [better](https://www.campaignmonitor.com/css/style-element/style-in-body/) support for styles in body but, **they're niche-ones**.

On other hand, **style in body** is against the best practices:

https://stackoverflow.com/questions/2830296/using-style-tags-in-the-body-with-other-html
and
https://stackoverflow.com/a/2830305/3943954
leading to
https://www.w3.org/TR/REC-html40/present/styles.html#edef-STYLE

> HTML permits any number of STYLE elements in the HEAD section of a document.

Personally, I think few niche mobile email software clients are not worth risk putting `style` blocks in the body. Furthermore, I process the HTML using [postcss-merge-rules](https://github.com/ben-eb/postcss-merge-rules) [and](https://github.com/hail2u/node-css-mqpacker) [others](https://github.com/ben-eb/postcss-discard-duplicates) which I fear might break if I used such non-conventional practices.

If you try to modularise the template and automate more, stray style blocks quickly will stand in the way. For example, if you're using Nunjucks+Gulp templating.

But that's my opinion, maybe I'm too lazy to test, it just never happens in my code =)

Thank you for sharing this 👍

**Comment by stojjan** [comment]
Hello, revelt!

Thanks for the quick reply. :)

Yep, I know sounds funky.
The reason I'm asking is that I need to create custom sections/blocks to work well with default templates 
 in Klaviyo email platform also with Drag&Drop functionality.
So I needed to a bit additional custom code for the sections and since I'm unable to add it to the default template...
So it's all good, but unfortunately haven't noticed that <style> in <body> isn't the best idea :)

Thank you,
Stojjan

**Comment by revelt** [comment]
Interesting!

From the workflow perspective, one way is to write `head` CSS "as required", and use them straight away in `body`, in-line. That's hand-coding scenario, but it's equally applicable to module management: you add a module into HTML and you add its CSS along, in a `<style>` nearby or in the `head`. Obviously it's more difficult to add it in `head` because you need to know where and it's not as easy to modularise, hence your trouble.

But there's other way.

Agree on CSS class name notation upfront. In in hand-coding scenario, that means memorise the common class names. In module management scenario, that means just define and stick to an agreed API of class names. THEN, generate ALL possible variations of all possible CSS styles and stick them in the `head`. This can be automated process and universal between different brands/clients/etc, just stick to the same naming schema. THEN, modules use whatever classes/id's they want. THEN, when assembly is done, during the **build** step, unused CSS is removed.

Second way's challenge is speed. Tool can't be JS-based because it's not compiled and not multi-threaded (I wrote one so I know the pain first-hand). But, any way you go, unused CSS removal is pretty much unavoidable anyway, isn't it?

This leads to a challenge of generating and managing already-generated CSS fast-enough to be considered real-time, and removing unused CSS, also fast-enough to be considered real-time.

**Comment by hteumeuleu** [comment]
I'm closing this issue as I'm not sure it exactly fits the bugs people look for in here. This is more a case of "_styles in the `<body>` are not well supported_".
